notifications:
  email: false

sudo: false
dist: trusty

language: c
compiler: gcc

addons:
  apt:
    packages:
      - ca-certificates
      - libgpgme11-dev
      - libnotmuch-dev
      - libtokyocabinet-dev
      - libkyotocabinet-dev
      - libgdbm-dev
      - libdb-dev
      - liblmdb-dev
      - libqdbm-dev
      - libslang2-dev
      - libgnutls-dev
      - libssl-dev
      - libsasl2-dev
      - libgss-dev
      - xsltproc
      - lynx
      - docbook-simple
      - docbook-xsl
      - libxml2-utils
      - gettext
      - lua5.2
      - liblua5.2-dev
      - autopoint
  coverity_scan:
    project:
      name: "neomutt/neomutt"
      description: "Teaching an Old Dog New Tricks"
    notification_email: rich@flatcap.org
    build_command_prepend: "./configure $OPTS"
    build_command: "make"
    branch_pattern: coverity

env:
  global:
    # encrypted COVERITY_SCAN_TOKEN for neomutt/neomutt
    - secure: "m1zPwjrCQFZzMaTiCSSB9xRV+Zq0q+AJ5R3EJHqS0a2I1wvOGjSCLi9/seryRSS6imVNuoOQr1hmVZVIoucPiwjdbL1KlTIiyDg3K6NemK+oVhT/CURhBcufCxQ2RLMyvPlpflX5dQvNIcdpT8UjSfP8piCbQY7JZGfPL/uiHNSBYbZeZS3W47wYEX6t6fGmfE9G6NceS9nU9/a4xsXEeMZQ6YoJNcKJB4OcTLqAFtTnNh5EfXtgMkxhN/9E0w+qJkumSRmmdDazRWTZ9iY+2ZZ6ZvEZUGOI5TWHHLyHrmq2j4CIxQYo8bSed+gTLSMsFajZMJ6JgBzkHl37gAzBD0MQwngKUsDvCVQFf/XoWDiHh8Qav5Q1FrFINaW87mUHkji+8ocPNenpdeWXUx6j2W+TV0Zf3p+53titU1GLCgaCYZpbgWF+vHonJZEyj72Xr6/vA4MxewJSqrRNodYHjdMDNIDonw9e0LC4cMnbVmJA2gP3XaiMvNRe9fOmhdeNoAqxIkAZHNl1D9lH4cS2dr7IQfNeCz4yos7Q6ULDq2PaJYhBBCeI8QtW6R4F19Jb5m0VS5FtzSkYd7jrJcrH28nJBByoWrrcbdxy6znZ07sjeMtDbQt4k0hNmqLEQ6gJR1zTr5EolmAiZvfMtYGZhqjLNA2ODUsP+4Nb5vNhj58="
  matrix:
    - OPTS="--disable-doc --disable-nls --flock --gpgme --lua --notmuch --bdb --with-domain=example.com --gdbm --gnutls --gss --homespool --kyotocabinet --lmdb --mixmaster --qdbm --sasl --disable-ssl --tokyocabinet"

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi

